-- =============================================================================
-- DEPRECADO — usar:
--   supabase/scripts/clean_database_for_seed.sql   (borrado completo demo + auth seed)
--   supabase/scripts/reset_operational_data.sql    (solo pedidos/cortes; conserva catálogo)
--   supabase/scripts/seed_catalog_stock.sql        (restaura stock canónico)
--   supabase/seed.sql                              (carga demo; incluye limpieza básica)
--
-- Orden en nube: clean_database_for_seed.sql → seed.sql
-- =============================================================================
