-- Generated by scripts/configure_supabase_push_secrets.sh — do not edit placeholders manually.
create extension if not exists pg_net with schema extensions;

do $$
declare
  v_url text := '__PUSH_SUPABASE_URL__';
  v_key text := '__PUSH_SERVICE_ROLE_KEY__';
  v_wh text := '__PUSH_WEBHOOK_SECRET__';
  v_id uuid;
begin
  if v_url = '' or v_key = '' or v_wh = '' then
    raise exception 'Push vault placeholders were not substituted';
  end if;

  select id into v_id from vault.secrets where name = 'push_supabase_url' limit 1;
  if v_id is not null then
    perform vault.update_secret(v_id, v_url, 'push_supabase_url', 'Supabase URL for push edge function');
  else
    perform vault.create_secret(v_url, 'push_supabase_url', 'Supabase URL for push edge function');
  end if;

  select id into v_id from vault.secrets where name = 'push_service_role_key' limit 1;
  if v_id is not null then
    perform vault.update_secret(v_id, v_key, 'push_service_role_key', 'Service role key for push edge function');
  else
    perform vault.create_secret(v_key, 'push_service_role_key', 'Service role key for push edge function');
  end if;

  select id into v_id from vault.secrets where name = 'push_webhook_secret' limit 1;
  if v_id is not null then
    perform vault.update_secret(v_id, v_wh, 'push_webhook_secret', 'Webhook secret for push edge function');
  else
    perform vault.create_secret(v_wh, 'push_webhook_secret', 'Webhook secret for push edge function');
  end if;
end;
$$;
